[project]
name = "anti-scam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ruff>=0.14.5",
    "playwright>=1.45.0",
    "pytest-playwright>=0.7.1",
    "tldextract>=5.1.2",
]
